const REQUEST_START = 'REQUEST_START';
const REQUEST_END = 'REQUEST_END';
const LOAD_ANIMALS = 'LOAD_ANIMALS';
const ADD_ANIMAL = 'ADD_ANIMAL';
const REMOVE_ANIMAL = 'REMOVE_ANIMAL';

export default {
  REQUEST_START,
  REQUEST_END,
  LOAD_ANIMALS,
  ADD_ANIMAL,
  REMOVE_ANIMAL,
};
